### ISSUE TITLE
Translating sky culture (via Github or transifex)?

### ISSUE THREAD

**Issue by sanketgarade** [Stellarium/stellarium-skycultures#17]
Hi

I want to add Marathi translation to sky cultures (Western and Indian Vedic)

Do directly modify the `.po` files in this repo and send a PR to merge those changes?
https://github.com/Stellarium/stellarium-skycultures/blob/master/indian/po/mr.po

OR 

do I do the translations on the transifex resource for the sky cultures?
https://www.transifex.com/stellarium/stellarium/po-stellarium-skycultures-stellarium-skycultures-pot--master/

**Comment by gzotti** [comment]
The simplest way is to register as translator on Transifex, and then translate.

**Comment by sanketgarade** [comment]
Ok understood. And at what point or based on what criteria are the translated strings used in the next release ? Both on the web and in the apps.

**Comment by sanketgarade** [comment]
Ok understood. And at what point or based on what criteria are the translated strings used in the next release ? Both on the web and in the apps.

**Comment by gzotti** [comment]
Strings are certainly grabbed before each release, and frequently in between for betas. Criterion is "existence of translation". Translation is a community process. Each supported language should have a responsible person to review and finalize translation, but also unreviewed strings are used, because it's usually better to have an approximate translation than none, and 3 developers cannot also review 80+ languages. It is expected that registered translators do not sabotage the project by injecting nonsense translations, or such nonsense is discovered and fixed quickly, and the saboteur banned from further action. 
This is the process for the desktop programs. I cannot comment on stellarium-web.
